name: simplified_ninja
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  google_fonts: ^2.3.1
  font_awesome_flutter: ^9.2.0
  intl: ^0.17.0
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.7
  dio: ^4.0.4
  flutter_image_slideshow: ^0.1.2
  fancy_shimmer_image: ^2.0.1+1
  flutter_bullet_list: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/


